---
# In this role I put all apt packages that I want to have installed for which I don't really care about the specific
# version.
- name: Ensure latets version of standard packages are up to date
  become: yes
  apt:
    pkg:
    - tree
